<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Invite Relatives";
	
	$theid = decode($request->id);
	if(isEmptyString($theid)){
		$theid = $personid;
	}
	$person = new Person();
	$person->populate($theid);
	
	$uninvited = $person->getUnInvitedPeople();
	$no_uninvited = $uninvited->count();
	// debugMessage($uninvited->toArray());
	
	$this->headTitle($title);
	
?>
<script>
	$(document).ready(function() {
		
		$(".xinvitetrigger").click(function(e){
			bootbox.alert('<label class="blockcontainer bolded">Invitation of relatives shall be available after Beta.</label>');
		});
	
		$(".xinvitetrigger, .invite").attr('title', 'Invitations not available in Beta');
		$(".datefield, .invite").attr('readOnly', 'true');
		$("a.invitetrigger").click(function(){
			var id = $(this).attr('id');
			var personid = $("label."+id).html();
			var email = $("input."+id).val();
			var invitedby = $("label."+id).attr('title');
			/*alert('id is '+id);
			alert('email is '+email);
			alert('invited by '+$("label."+id).html());*/
			if(isEmptyString(email)) {
				$("div#invite_"+personid+"_error").html('<div class="alert alert-error">Please enter email to invite</div>');
				$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			}
			if(!isEmptyString(email) && !validateEmail(email)) {
				$("div#invite_"+personid+"_error").html('<div class="alert alert-error">Please enter a valid email</div>');
				$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			}
			// check that email is provided
			if(!isEmptyString(email) && validateEmail(email)) {
				$("div#invite_"+personid+"_error").html('');
				$("span#inv_before_"+personid).hide(); 
				$("span#inv_after_"+personid+" a").show(); 
				// post 
				$.post(  
					"<?php echo $this->baseUrl("person/inviteone"); ?>", {id: personid, email: email},  
					function(data){
						// alert(data);
						if(data.search("Success") != -1){								
							// reload parent on close				
							$("span#inv_after_"+personid).html(data);	
							$("span#inv_hide_"+personid).hide(); 			
						} else {
							var err = 'An error occured while inviting user. Try again later';
							$("span#inv_after_"+personid).html(err);
						}
						// location.reload(true);
						$("span#inv_after_"+personid+" a").hide(); 
						$("div.alert-success").css({'background': 'url("<?php echo $this->baseUrl('images/tick.png'); ?>") no-repeat #FEF0B6 5px 8px'});
					}  
				); // close the $.post
			}
		});
	}); 
</script>
<style>
body {
	overflow:hidden;
}
.table td {
	vertical-align:middle;
}
</style>
<div id="popupdiv">
<form class="form-horizontal well span6" id="inviteform" method="post" style="max-height:400px; overflow-y:scroll;">
    <table class="table margin0 border0">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
        <tbody>
        	<?php if($no_uninvited == 0){ ?>
            	<tr>
                	<td colspan="3">You currently have got no relatives to invite</td>
                </tr>
            <?php } else { ?>
            	<?php 
					foreach($uninvited as $profile){ 
						$firstname = $profile->getFirstName();
				?>
                <tr>
                	<td width="120" class="nowrapping"><?php echo $profile->getName(); ?></td>
                    <td>
                    	<span class="inv_before" id="inv_before_<?php echo $profile->getID(); ?>">
                            <input type="text" name="email_<?php echo $profile->getID(); ?>" id="email_<?php echo $profile->getID(); ?>" placeholder="enter email" title="Invite <?php echo $firstname; ?> to your Family Tree" value="<?php echo $profile->getEmail(); ?>" class="invite autoinvite invite_<?php echo $profile->getID(); ?>" /><a href="javascript:doNothing();" class="btn btn-primary btn-gold xinvitetrigger" style="opacity:0.3;" id="invite_<?php echo $profile->getID(); ?>" title="Invite <?php echo $firstname; ?> to join <?php echo $this->translate('appname'); ?>"><i class="icon-envelope"></i> <?php echo $this->translate('person_button_invite'); ?></a>
                            <label class="hide invite_<?php echo $profile->getID(); ?>" title="<?php echo $personid; ?>"><?php echo $profile->getID(); ?></label>                            
                            <div id="invite_<?php echo $profile->getID(); ?>_error" style="margin-top:4px;"></div>
                        </span>
                        <span class="inv_after" id="inv_after_<?php echo $profile->getID(); ?>">
                            <a id="loading_<?php echo $profile->getID(); ?>" class="hidden"><img style="margin-left:0" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
                        </span>
                    <td></td>
                </tr>
				<?php } ?>
            <?php } ?>
        </tbody>
  </table>
</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
