<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$orgname = new OrganisationName();
	
	$clan = new Clan(); 
	$clanid = $request->clanid;
	if(!isEmptyString($clanid)){
		$clan->populate(decode($clanid));
		$type = $request->type;
		$orgname->setType($type);
		$orgname->setOrganisationID($clan->getID());
	}
	
	$posturl = $this->baseUrl("clan/processaddname");
	$button_title = $this->translate("clan_button_newname"); 
	
	// update 
	$id = $request->id;
	if(!isEmptyString($id)){
		$orgname->populate(decode($id));
		$type = $orgname->getType();
		$button_title = $this->translate("clan_button_editname"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$orgname->processPost($session->getVar(FORM_VALUES));	
	}
	
	$title = "Clan Names";
	$this->headTitle($title);
	
	$isadmin = false;
	if(isAdmin()){
		$isadmin = true;
	}
	
?>
<div class="popupdiv">
<form class="form-horizontal well span6" id="nameform" action="<?php echo $posturl; ?>" method="post">
    <table class="table">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
        <tr>
            <td width="30%"><label class="control-label" for="name"><?php echo $this->translate("clan_addname_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td width="70%">
            <?php if($isadmin){ ?>
            <input type="text" name="name" id="name" class="span3 hastooltip" value="<?php echo $orgname->getName(); ?>" title="<?php echo $this->translate("clan_name_tooltip"); ?>"  />
            <?php } else { ?>
            	<?php echo $orgname->getName(); ?>
            <?php } ?>
            <div id="name_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label" for="description"><?php echo $this->translate("clan_addname_description_label"); ?>:</label></td>
            <td>
            <?php if($isadmin){ ?>
            	<input type="text" name="description" id="description" class="span4 hastooltip expanding" value="<?php echo $orgname->getDescription(); ?>" title="<?php echo $this->translate("clan_addname_description_tooltip"); ?>"  />
            <?php } else { ?>
            	<?php echo isEmptyString($orgname->getDescription()) ? '--': $orgname->getDescription(); ?>
            <?php } ?>    
            </td>
        </tr>
        <tr>
            <td style="vertical-align:top;"><label class="control-label" for="notes"><?php echo $this->translate("clan_addname_notes_label"); ?>:</label></td>
            <td style="vertical-align:top;">
            <?php if($isadmin){ ?>            	
				<textarea style="min-height:100px;" name="notes" id="notes" class="span4 hastooltip" title="<?php echo $this->translate("clan_addname_notes_tooltip"); ?>"><?php echo $orgname->getNotes(); ?></textarea>
            <?php } else { ?>
            	<?php echo isEmptyString($orgname->getNotes()) ? '--': $orgname->getNotes(); ?>
            <?php } ?>       
              	<input type="hidden" name="entityname" value="OrganisationName" />
			    <input type="hidden" id="id" name="id" value="<?php echo encode($orgname->getID()); ?>" />
			    <input type="hidden" id="type" name="type" value="<?php echo $orgname->getType(); ?>" />
                <input type="hidden" id="organisationid" name="organisationid" value="<?php echo $orgname->getOrganisationID(); ?>" />
			    <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('clan/addname/clanid/'.encode($orgname->getOrganisationID())."/pgc/true/type/".$type)); ?>" />			   				
                <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('clan/addnamesuccess')); ?>" />
                <div id="organisationid_error"></div>
              </td>
        </tr>
  </table>
</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
<script>
	$(document).ready(function() {
		$("#nameform").validate({		
			// define the validation rules one field at a time
			rules: {
				name: "required",
				organisationid: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				name: "<?php echo "Please enter name"; ?>",
				organisationid: "<?php echo "Clan not specified"; ?>"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		// tooltips in popup
		$(".hastooltip").each(function(){		
			var theid = $(this).attr('id');
			var thepath = '<?php echo $this->baseUrl('images/questionmark.png'); ?>';
			if($(this).attr('title') != "undefined" || $(this).attr('title') != ""){
				$('<a href="javascript: void(0);" class="qcontainer" id="q_'+theid+'"><img src="'+thepath+'" /></a>').insertAfter(this);
				$("#q_"+theid).attr('title', $(this).attr('title')).addClass('qtooltip');
			}	    
		}); 
		$('.qtooltip').tipsy({fade: true, gravity: 'w', html: true, trigger: 'hover', offset: -5});
    	$(".hastooltip").attr('title','');
		
		// reset tab index
		var tabindex = 1;
		$('input,select').each(function() {
			if (this.type != "hidden") {
				var $input = $(this);
				$input.attr("tabindex", tabindex);
				tabindex++;
			}
		});
		
		<?php if(!$isadmin){ ?>
			$(".modal-footer #save").remove();
		<?php } ?>
	}); 
</script>
<style>
body {
	overflow:hidden;
}
</style>