<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Benefits";
	$this->headTitle($this->translate("appname")." | ".$title); 

?>
<div class="row marginleft0">
    <div class="span8 pull-left marginleft0 public_leftcolumn">
        <div class="content">
        <h1><?php echo $title; ?></h1> 
        <p>The benefits of a GandaAncestry membership are many and truly unique. There no other place in the world, on or off the Internet, where a Muganda can build a family tree that is based on the Baganda clan system and share it with family and friends using state of the art social networking tools.</p>
        
        <h2>Personal Identity and Pride</h2>
        <p>We are an island of freedom and privilege for you to proudly assert and celebrate your Baganda identity without guilt or apology. The information that you confirm and add about your clan, ssiga and other attributes should provide you with answers about who you are, where you came from and where you can go.As your family tree grows bigger your sense of belonging, to family, clan and the Baganda community should only get stronger.</p>
        
        <h2>Better Family Relationships</h2>
        <p>GandaAncestry provides you with unique opportunities to closely work with immediate family members such as spouse, children, siblings and parents, to organize and share family history and ancestry. The shared pain and triumph involved in building a family tree that is readily accessible to all family members can serve as glue to strengthen communication and relationships across your whole family.</p>
        
        <h2>Better Community Relationships</h2>
        <p>The information that GandaAncestry allows you to include in your personal profiles and family trees is increasing in variety and volume with time. Normally, a member needs to communicate and share family information with many relatives in order to build and maintain a large and diverse family tree. Indeed, you should expect to discover some totally new relatives that you have never met or heard about.</p>
        <p>GandaAncestry makes it possible for you to expand the breadth, depth and quality of the personal relationships that you can maintain within your extended family and across the Baganda clan ecosystem.</p>
        
        <h2>Education</h2>
        <p>As GandaAncestry member, you have access to a lot of high quality educational information about the Buganda Kingdom, Kabaka, Baganda clans and people with Baganda ancestry. If you are a parent, mentor or educator, the clarity about your own Baganda roots plus the available education information can be invaluable in teaching family members and others about your heritage.</p>
        </div>
    </div>
    <?php require APPLICATION_PATH."/views/scripts/index/righthandband.phtml"; ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
