<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$word = $request->word;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="../stylesheet/gandaancestry.css" rel="stylesheet" type="text/css">
<title>Ganda Ancestry Dictionary Pronunciation</title>
</head>

<body  text="#000080" vlink="#000080" alink="#000080" link="#000080" bgcolor="#e8e8d0" onLoad=self.focus();>
<table width="200" border="0" align="center" bgcolor="#ffffff">
  <tr>
    <td><img src="<?php echo $this->baseUrl('/images/logogrey.png');?>"></td>
  </tr>
  <tr>
    <td><div align="center"><br>
        <font 
            face=Arial color=#000000 size=3>Audio pronunciation for<br>
        <b>"<?php
	  	echo $word; ?>"</b></font><br>
        
	  <a href="<?php echo $this->baseUrl('lugandadictionary/audio/word/'.$word);?>">
	 
        <span class="infoanchor">hear it again</span><img src="<?php echo $this->baseUrl("/images/audioicon.gif");?>" width="13" height="21" hspace="2" border="0" align="absbottom"></a></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>    
			<EMBED src="<?php echo $this->baseUrl('/audio/'.$word.'.mp3');?>" hidden="true" AUTOSTART="true">	
	  
	<table cellpadding=0>
              <tbody>
              <tr>
                <td width=5><img height=1 
                  src="Merriam-Webster Pronunciation_files/pixt.gif" width=5> 
</td>
                <td><br><font face=Arial size=1><b>If the voice is not clear, <br>* 
				  
				  	 <a href="<?php echo $this->baseUrl('/audio/'.$word.'.mp3');?>">
				  Click here to 
                  listen with your default audio player</a>. <br>
                </b></font></td>
              </tr></tbody></table>       
</td>
  </tr>
</table>
</body>
</html>
