<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$person = new Person(); 
	$posturl = $this->baseUrl("announcement/processapply");
	
	$ssiga = "";
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$formvalues = $session->getVar(FORM_VALUES);
		$ssiga = $formvalues['ssiga']; unset($formvalues['ssiga']); 
		$person->processPost($formvalues);	
	}
	
	$title = "Apply for Beta";
	$this->headTitle($title);
	
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			rules: {
				firstname: "required",
				lastname: "required",
				clanname: "required",
				clanid: "required",
				ssiga: "required",
				email: {
					required: true, 
					email: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {	
				firstname: "<?php echo $this->translate("person_firstname_error"); ?>",
				lastname: "<?php echo $this->translate("person_lastname_error"); ?>",
				clanname: "<?php echo $this->translate("person_clanname_error"); ?>",
				clanid: "<?php echo $this->translate("person_clanid_error"); ?>",
				ssiga: "Please enter your Ssiga",
				email: {
					"required": "<?php echo $this->translate("useraccount_email_error"); ?>", 
					"email": "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		$("#contentwrapper").removeClass('well');
		
		$("#closewindow").click(function() {
			window.close();
		});	
	}); 
</script>
<style>
#loginheader, #footertable, #betalogo, #headeractions {
	display:none;
}
body {
	font-family:'calibri','Telex',sans-serif;	
}
body.publicbody .footer.well {
	height:30px;
	min-height:0;
}
.popupdiv .form-horizontal .control-label {
	font-size:15px;
}
#clanid {
	width:215px;
}
.btn-primary.btn-gold {
	font-weight:bold;
	-webkit-border-radius: 12px;
	-moz-border-radius: 12px;
	border-radius: 12px;
	padding:8px 25px 8px 25px;
	font-size:16px;
	border-color: #C1A118;
}
</style>
<div class="popupdiv well span7" style="margin-left:170px;">
<form class="form-horizontal " id="indexform" action="<?php echo $posturl; ?>" method="post">
	<h3 class="well-legend" style="text-align:center;">Apply to be a Beta User</h3></legend>
    <table class="table">
		<?php if($sessionhaserror || $request->success == 'error') { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
        <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) || $request->success == 'true'){ ?>
            <tr>
	        	<td colspan="2">
                	<div class="alert alert-success" style="text-align:left; display:block;">Application successfully sent.</div>
                    <span class="pagedescription" style="font-size:18px; font-style:normal;">
                       Thank you for your interest in the GandaAncestry beta user program. We will review your application and respond to you as soon as possible, depending on the volume of requests received.
                    </span>
                </td>
            </tr>
        <?php } else { ?>	
        <tr>
            <td colspan="2">
            <span class="pagedescription" style="font-size:18px; font-style:normal;">Thank you for your interest in the GandaAncestry beta user program. Please complete all fields on the form below to apply. We shall respond to you by email as soon as possible.</span><td>
        </tr>
        <tr>
            <td width="30%"><label class="control-label leftalign"><?php echo $this->translate("person_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input name="firstname" id="firstname" type="text" class="span3" value="<?php echo $person->getFirstName(); ?>" /><div id="firstname_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label leftalign"><?php echo $this->translate("person_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
       		<td><input name="lastname" id="lastname" type="text" class="span3" value="<?php echo $person->getLastName(); ?>" /><div id="lastname_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label leftalign">Clan Name: <?php echo $this->translate("global_required_field_marker"); ?></label>
            	<span class="pagedescription">(e.g., Mugerwa)</span>
            </td>
            <td><input class="span3" name="clanname" id="clanname" type="text" value="<?php echo $person->getClanName(); ?>" /><div id="clanname_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label leftalign"><?php echo $this->translate("person_email_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input class="span3" name="email" id="email" type="text" value="<?php echo $person->getEmail(); ?>" /><div id="email_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label leftalign">Ekika (Clan): <?php echo $this->translate("global_required_field_marker"); ?></label>
            	<span class="pagedescription">(e.g., Nkima)</span></td>
            <td>
            <?php
				$clanlookup = new LookupType();
				$clanlookup->setName("ALL_CLANS");
				$clandropdown = new Zend_Form_Element_Select('clanid',
					  array(
							  'multiOptions' => array_merge_maintain_keys(array('' => '<Select Clan>'), $clanlookup->getOptionValuesFromQuery()),
							  'view' => new Zend_View(),
							  'decorators' => array(array('ViewHelper')),
							  'class' => array('span3'),
					  )
				);
				
				$clandropdown->setValue($person->getClanID());
				echo $clandropdown->render();
			?><div id="clanid_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label leftalign">Ssiga: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input class="span3" name="ssiga" id="ssiga" type="text" value="<?php echo $ssiga; ?>" /><div id="ssiga_error"></div></td>
        </tr>
        <tr>
            <td></td>
            <td class="nowrapping">
            <button type="submit" id="submitjoin" class="btn btn-primary btn-gold">Apply Now</button>
            <input type="hidden" name="entityname" value="Beta" />
			    <input type="hidden" id="id" name="id" value="" />
                <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('announcement/apply')); ?>" />
            </td>
        </tr>
        <?php } ?>
  </table>
</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>