<table style="width:700px; margin:0; padding:25px 25px 25px 15px; background-color:#fafdff; font-family: Arial, Helvetica, Tahoma, sans-serif; font-size:15px; line-height: 1.2em;">
	<tr>
        <td colspan="2" style="padding-bottom:10px; padding-top:10px; text-align:center; border-bottom: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
            <a class="brand" id="thelogo" href="<?php echo $this->serverUrl($this->baseUrl()); ?>"><img alt="<?php echo $this->appname; ?>" src="<?php echo $this->serverUrl($this->baseUrl("images/logogrey.png")); ?>" /></a>
        </td>
    </tr>    
    <tr>
    	<td>
            Dear Admin,<br /><br />
            
            This is to inform you of a new <?php echo $this->appname; ?> beta user application that has been received with the following details;<br /><br />
            <b>Name: </b><?php echo $this->name; ?><br />
            <b>Email: </b><?php echo $this->email; ?><br />
            <b>Clan: </b><?php echo $this->clan; ?><br /><br />
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding:10px 0 10px 0; text-align:center; border-top: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
           &nbsp;Copyright &copy; 2012 <?php echo $this->appname; ?>. All Rights Reserved.
        </td>
    </tr>
</table>