<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
Dear <?php echo $this->firstname; ?>,<br /><br />

Thank you for your very kind donation of <b>$<?php echo $this->amount; ?></b>, which we received today. 
Your generosity will help us to move forward. You are making a difference!<br /><br />
Thanks again for your kindness

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>