 			<?php echo $this->translate("companyname"); ?> Team.<br />
            <?php echo $this->serverUrl($this->baseUrl()); ?>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding:10px 0 10px 0; text-align:center; border-top: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
           <?php echo sprintf($this->translate("copyright"), date("Y"), $this->translate("companyname")); ?>
        </td>
    </tr>
</table>
