<table style="width:700px; margin:0; padding:15px; background-color:#fafdff; font-family:'calibri','Telex',sans-serif; font-size:16px; line-height: 1.2em;">
	<tr>
        <td style="padding-bottom:10px; padding-top:10px; padding-left:15px; text-align:left; border-bottom: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
            <a class="brand" id="thelogo" href="<?php echo $this->serverUrl($this->baseUrl()); ?>"><img alt="<?php echo $this->appname; ?>" src="<?php echo $this->serverUrl($this->baseUrl("images/logogrey.png")); ?>" /></a>
        </td>
    </tr>    
    <tr>
    	<td style="padding-bottom:25px; padding-top:10px; padding-left:15px; text-align:left;"><br />
        	