<table style="width:850px; margin:0; padding:25px 25px 25px 15px; background-color:#fafdff; font-family: Arial, Helvetica, Tahoma, sans-serif; font-size:15px; line-height: 1.2em;">    
    <tr>
        <td colspan="2" style="padding-bottom:10px; padding-top:10px; text-align:center; border-bottom: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
            <a class="brand" id="thelogo" style="" href="<?php echo "http://beta.gandaancestry.com"; ?>"><img alt="GandaAncestry" src="<?php echo "http://beta.gandaancestry.com/images/logogrey.png"; ?>" /></a>
        </td>
    </tr>
    <tr>
    	<td>
			Dear Friend,<br /><br />
            
            <?php if(!isEmptyString($this->intromsg)){ ?>
				<?php echo $this->intromsg; ?><br /><br />
            <?php } ?>
            
			<table style="margin:0 auto; background:none; width:940px;">                
                <tr>
                    <td colspan="2" style="text-align:center; display:block; font-size:13px; font-family:'calibri','Telex',sans-serif;">
                        Not able to view this email properly? <a href="<?php echo "http://beta.gandaancestry.com"; ?>">Click here to view it online</a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="display:inline-block; font-weight:bold; font-size:26px; margin:10px 0 0 0; color:#000000; width:100%; text-align:center; font-family:'calibri','Telex',sans-serif;">
                    Announcing Baganda Website GandaAncestry</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:justify; display:block; font-size:20px; line-height:28px; margin-bottom:15px; padding:0 70px 0 70px; color:#303030; font-family:'calibri','Telex',sans-serif;">We are pleased to announce GandaAncestry, the first and only Baganda family networking website. It allows you to build your family tree based on the Baganda clan system and to securely share it with relatives and friends.</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:center; padding-bottom:15px;">
                        <img alt="GandaAncestry Announcement" src="<?php echo "http://beta.gandaancestry.com/images/launch.png"; ?>" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:left; padding-bottom:15px; display:block; font-size:20px; line-height:28px; margin-bottom:15px; padding:0 70px 0 70px; color:#303030; font-family:'calibri','Telex',sans-serif; text-align:left; padding-left:70px;">
                    GandaAncestry announced on <b>October 8, 2012</b> to commemorate <b>50 years</b> since Buganda  received her independence from the British. The website will be available to a limited number of users (beta users) until <b>November 19, 2012.</b></td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:left; padding-bottom:15px; display:block; font-size:20px; line-height:28px; margin-bottom:15px; padding:0 70px 0 70px; color:#303030; font-family:'calibri','Telex',sans-serif; text-align:left; padding-left:70px; padding-right:10px;">
                    GandaAncestry will be officially launched on <b>November 19, 2012</b>, in honor of the <b>88th</b> birthday anniversary of Ssekabaka Muteesa II, father of beloved Kabaka Muwenda Mutebi II.</td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:left; padding-bottom:15px; display:block; font-size:20px; line-height:28px; margin-bottom:15px; color:#303030; font-family:'calibri','Telex',sans-serif; text-align:left; padding-left:70px;">
                        <img alt="President, GandaAncestry" title="President, GandaAncestry" src="<?php echo "http://beta.gandaancestry.com/images/presidentsign.png"; ?>" al /><br />(Mmamba) <br />President, GandaAncestry.
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:center; padding-bottom:30px; display:block; font-size:20px; line-height:28px; margin-bottom:15px; padding:0 70px 0 70px; color:#303030; font-family:'calibri','Telex',sans-serif;">
                    <a id="apply" style="width:268px; 61px;" href="<?php echo "http://beta.gandaancestry.com/announcement/apply"; ?>" title="Apply to Be A Beta User"><img src="<?php echo $this->serverUrl($this->baseUrl('images/applybeta.png')); ?>" alt="Apply to Be A Beta User" title="Apply to Be A Beta User" /></a>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:center; display:block; font-size:20px; line-height:28px; margin-bottom:15px; padding-top:30px; color:#303030; font-family:'calibri','Telex',sans-serif;"><a style="font-size:16px;" href="<?php echo "http://beta.gandaancestry.com/announcement/tellfriend"; ?>">Forward this message to a friend</a>
                       
                    </td>
                </tr>
            </table>
		</td>
    </tr>
    <tr>
    	<td style="text-align:center"><a href="<?php echo "http://beta.gandaancestry.com"; ?>" title="Click for more details">Not able to view this email properly? Click here to view it online</a>
</td>
    </tr>
    <tr>
        <td colspan="2" style="padding:10px 0 10px 0; text-align:center; border-top: 3px solid #E2E2E2; background:none repeat scroll 0 0 #F4F4F4;">
           &nbsp;Copyright &copy; 2012 GandaAncestry. All Rights Reserved.
        </td>
    </tr>
</table>
