<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Report abuse of GandaAncestry Services";
	$this->headTitle($title);
	
	$person = new Person();
	if(!isEmptyString($personid)){
		$person->populate($personid);
	}
	
	$posturl = $this->baseUrl("contactus/processreport");
?>
<script>
	$(document).ready(function(){
		// validation code for the form
		$("#indexform").validate({
			// define the validation rules one field at a time
			rules: {
				type: "required",
				name: "required",
				gender: "required",
				email: {
					required: false,
					email: true
				},
				youremail: {
					required: true,
					email: true
				},
				message: "required",
				code: {
					required: true,
					validatecode: true					
				}
			}, 
			// the messages for each of the fields being validated
			messages: {
				type: "Please select a violation type",
				name: "Please enter your Name",	
				gender: "<?php echo $this->translate("person_gender_error"); ?>",
				email: {
					email: "Please enter a valid Email Address"
				},
				youremail: {
					required: "Please enter your Email Address",
					email: "Please enter a valid Email Address"
				},
				message: "Please enter your message",
				code: {
					required: "Enter the code you see in blue"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		$.validator.addMethod("validatecode", function(value, element, params) {
			//alert('code is '+value); //alert('valid is '+$("#validcode").val());
			if ($("#code").val().toLowerCase() == $("#validcode").val().toLowerCase()) {
				return true; 
			}
			return false;        
		}, "Captcha Invalid! <br />Re-enter code or refresh for a new one");
		
		// refresh captcha
		$('img#refresh').click(function() { 			
			change_captcha();
		});
		
		$('img#refresh').click();
		function change_captcha(){
			$("#code").val(''); 
			$.get("<?php echo $this->baseUrl('signup/getcaptcha'); ?>", 
				// parameters for the request along with a cachebuster to stop IE from caching the request
				{cachebuster: new Date().getTime()}, 			   
				function(data){			
					//alert(data);
					$("#validcode").val(data); 
					$("#captcha").html(data).css({'font-size':'14px'});			
				}
			);
		}
		
	}); 
</script>
<style>
.form-horizontal .control-label {
	font-size:16px;
	color:#333333;
	width:auto;
	font-weight:normal;
}
</style>
<div class="row marginleft0">
    <div class="span8 pull-left marginleft0 public_leftcolumn">
        <div class="content">
        	<div class="well row span9" style="margin:0 auto; display:block; width:688px;">
				<form class="form-horizontal " id="indexform" action="<?php echo $posturl; ?>" method="post">
                    <h3 class="well-legend" style="text-align:center;"><?php echo $title; ?></h3></legend>
                    <table class="table">
                        <?php if($sessionhaserror || $request->result == 'error') { ?>
                            <tr>
                                <td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                            </tr>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) || $request->result == 'success'){ ?>
                            <tr>
                                <td colspan="2">
                                    <div class="alert alert-success" style="text-align:left; display:block;">Report successfully submitted</div>
                                    <span class="pagedescription" style="font-size:18px; font-style:normal;">
                                        Thank you for your effort in helping us improve GandaAncestry. We have received your query and we shall respond to you as soon as possible.
                                        <br /><br />
                                        GandaAncestry Team.
                                    </span>
                                </td>
                            </tr>
                        <?php } else { ?>	
                        <tr>
                            <td colspan="2">
                                <span class="pagedescription" style="font-size:18px; font-style:normal;">
                                    Please use this form to report any potential violation or abuse of the GandaAncestry Services. 
                                    All fields marked with <?php echo $this->translate("global_required_field_marker"); ?> are mandatory.
                                </span>
                            <td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <h2>What type of potential abuse are you reporting? <?php echo $this->translate("global_required_field_marker"); ?></h2>
                            <td>
                        </tr>
                        <tr>
                            <td colspan="2">
                            	<div id="type_error"></div>
                                <?php 
									$types = getViolationTypes();
									foreach($types as $key => $value){
								?>
                                	<label class="radio zendradio"><p><input type="radio" name="type" id="type_<?php echo $key; ?>" value="<?php echo $key; ?>" />&nbsp; <?php echo $value; ?></p></label>
                                <?php } ?>
                                
                            <td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <h2>Information about person you are reporting:</h2>
                                <table class="table noborder margin0">
                                	<tr>
                                    	<td width="25%;"><label class="control-label leftalign">Name: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                        <td width="35%;"><input name="name" id="name" type="text" class="span3" style="padding:6px; width:90%;" value="<?php echo $person->getName(); ?>" /><div id="name_error"></div></td>
                                        <td width="15%%;"><label class="control-label leftalign">Country:</label></td>
                                        <td><?php
												$countries = getCountries();
												unset($countries['UG']);
												// debugMessage($countries['XX']);
												$countrydropdown = new Zend_Form_Element_Select('country',
																	array(
																		'multiOptions' => array_merge_maintain_keys(array('' => "<Select one>","XX"=>"Buganda","UG"=>"Uganda"), $countries),
																		'view' => new Zend_View(), 
																		'decorators' => array('ViewHelper'),
																		'class' => array('span3','country','xhastooltip')
																	)
																);
												$countrydropdown->setValue(''); 
												echo $countrydropdown->render(); 
											?><div id="country_error"></div></td>
                                    </tr>
                                </table>
                            <td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <h2>Information about yourself:</h2>
                                <table class="table noborder margin0">
                                	<tr>
                                    	<td width="25%;"><label class="control-label leftalign">Email Address: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                        <td width="35%;"><input style="padding:6px; width:90%;" class="" name="youremail" id="youremail" type="text" value="<?php echo $person->getEmail(); ?>" /><div id="youremail_error"></div></td>
                                        <td width="15%;"><label class="control-label leftalign">Country: </label></td>
                                        <td><?php
												// debugMessage($countries['XX']);
												$countrydropdown = new Zend_Form_Element_Select('yourcountry',
																	array(
																		'multiOptions' => array_merge_maintain_keys(array('' => "<Select one>","XX"=>"Buganda","UG"=>"Uganda"), $countries),
																		'view' => new Zend_View(), 
																		'decorators' => array('ViewHelper'),
																		'class' => array('span3','country','xhastooltip')
																	)
																);
												$countrydropdown->setValue(''); 
												echo $countrydropdown->render(); 
											?><div id="yourcountry_error"></div></td>
                                    </tr>
                                </table>
                            <td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <table class="table noborder margin0">
                                	<tr>
                                    	<td width="25%;" style="padding-left:0;"><label class="control-label leftalign" style="font-size:18px; font-weight:bold; color:#666666; margin-left:0;">Description of Abuse or Violation: </label></td>
                                        <td><textarea name="message" id="message" class="span4 expanding pull-right" style="min-height:100px; width:99%; float:right;"></textarea><div id="message_error"></div></td>
                                    </tr>
                                </table>
                            <td>
                        </tr>
                        <tr>
                            <td style="width:25%;"></td>
                            <td class="padding0">
                            	<table class="table noborder margin0">
                                	<tr>
                                    	<td width="30%;" style="padding-left:0;"><label class="control-label captcha">Captcha: <?php echo $this->translate("global_required_field_marker"); ?></label><span class="pagedescription">(enter the codes you see in blue)</span></td>
                                        <td>
                                            <span style="display:block;">
                                                <div id="wrap" class="public" align="center">
                                                    <label id="captcha"></label>
                                                    <input name="code" type="text" id="code" style="width:80px;" value="" />
                                                    <input name="validcode" type="hidden" id="validcode" value="" />
                                                </div>
                                                <img src="<?php echo $this->baseUrl('images/refresh.jpg'); ?>" width="25" alt="Refresh Captcha Code" id="refresh" />                        					</span>
                                            
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td style="border:none;"></td>
                            <td style="border:none;"><div id="code_error"></div> </td>
                        </tr>
                        <tr>
                            <td colspan="2" class="rightalign"><button type="submit" id="submit" class="btn btn-primary btn-gold btn-large bolded">Submit</button></td>
                        </tr>
                        <?php } ?>
                  </table>
                </form>
            </div>
        </div>
    </div>
    <?php require APPLICATION_PATH."/views/scripts/index/righthandband.phtml"; ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
