<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Buganda Clans";
	$this->headTitle($this->translate("appname")." | Clans"); 
	
	$searchnames = '';
	if(!isEmptyString($request->searchterm)){
		$searchnames .= $request->searchterm;
	}
	if (!isEmptyString($request->letter)){
		$searchnames .= "Browse By: <b>".strtoupper($request->letter)."</b>";
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.shortname","c.fullname","c.engname","c.omubala","c.akabbiro","c.leader"));
	$paginate->setDefaultSortBy("c.fullname");	
	$paginate->setDefaultSortOrder("ASC");
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = "";
	
	$searched = true;
	if(!isEmptyString($request->searchterm)){
		$where_query .= " AND (c.fullname LIKE '%".$request->searchterm."%') ";
		$searched = true;
	}
	
	if (!isEmptyString($request->letter)){
		$where_query .= " AND (`c`.`fullname` LIKE '".$request->letter."%') ";
		$searched = true;
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT c.id, c.shortname, c.fullname as `Clan Name`, c.omubala, c.akabbiro, c.leader, c.bio c FROM organisation c WHERE c.type = '1' ".$where_query."  ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$paginate->getSortSQL();
	
	// debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	// debugMessage($result);

?>
<script>
$(document).ready(function(){		
	// set hidden field for the alphabet and submit the form
	$(".alphabet").click(function(){
		var letter = $(this).attr('id');
		// alert(letter);
		$('#letter').val(letter);
		$('#searchterm').val('');
		$("#searchform").submit();
	});
}); 
</script>
<style>
.public_leftcolumn {
	width:70%;
}
.public_leftcolumn .content {
	width:100%;
}
.public_rightcolumn {
	margin-left:5px; 
	width:250px;
}
ul#searchbox {
	width:100%; 
	margin-bottom:20px;
	margin-top:-45px;
}
ul#bagandalist {
	clear:both;
	border-top:2px solid #DDDDDD;
	margin-top:8px;
}
ul#bagandalist li {
	border-bottom:dashed 1px #D1D1D1;
}
ul#bagandalist li:hover {
	background-color:#E1F0F6;	
}
ul#bagandalist li .control-label {
	color:#707070;
}
ul#bagandalist li table.itemlist td {
	padding:2px;	
}
.searchedterm {
	display:inline-block; 
	width:265px; 
	clear:both; 
	padding-top:12px;
}
.paginatecustom {
	margin-bottom:15px; 
	margin-top:10px; 
	width:370px; 
	display:inline-block; 
	float:right;
	text-align:right;
}
</style>
<div class="row marginleft0">
    <div class="span11 pull-left marginleft0 public_leftcolumn">
    <form action="<?php echo $this->baseUrl("clans/indexsearch"); ?>" method="get" id="searchform" class="form-search">
    <h1><?php echo $title; ?></h1>  
        <div class="wellcontent" style="position:relative;">
          <ul class="nav pagination pull-right" id="searchbox">
          	<li>
            	<a style="padding-left:0; padding-right:0; float:right;" class="pull-right">
                    <table id="directorysearchtable" class="table noborder margin0">
                        <tr>
                            <td style="padding-top:10px;"><label style="font-size:12px; color:#777777;" class="control-label leftalign margin0">Find a Clan:</label></td>
                            <td style="padding-top:10px;"><input name="searchterm" id="searchterm" type="text" class="span2 padding3" value="<?php echo $request->searchterm; ?>" placeholder="Searchterm" /></td>                            
                            <td style="padding-top:10px;"><button type="submit" id="searchbutton" class="btn" style="padding:6px 10px"><i class="icon-search"></i></button>
                            <input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" /></td>
                        </tr>
                    </table>
                </a>
            </li>
          </ul>
          <div class="alphabetlist pull-left"><?php echo $paginate->getAlphabetString(); ?></div>
          <label class="searchedterm control-label pull-left leftalign" style=""><?php echo $searchnames; ?></label>
            <div class="paginatecustom">
				<?php if(!$has_no_data){ ?>
                    <?php echo sprintf($this->translate("clan_list_counter"), $paginate->getItemCounterText()); ?> | 
                <?php } ?>
                <a href="<?php echo $this->baseUrl('clans'); ?>" title="Reset list to view all Clans">Reset</a>
            </div>
            <?php if($has_no_data){ ?>
            	<div style="clear:both;" class="alert alert-info"><?php echo $this->translate("clan_list_norecords"); ?></div>
            <?php } else { ?>
            <ul id="bagandalist" class="nav nav-stacked">
				<?php 				  		
                    foreach($result as $line){
                        $clan = new Clan();
						$clan->populate($line['id']);
						
						if($clan->getName() != 'Mmamba Kakoboza'){
                ?>
                    <li>
                        <table class="table noborder margin0">
                        	<tr>
                            	<td width="120">
                                    <div class="profileinfo clantotem_thumb">
                                        <a class="picbg" href="<?php echo $this->baseUrl('clan/view/id/'.encode($clan->getID())); ?>" title="Details of <?php echo $clan->getName(); ?>"><img id="coverlogo" src="<?php echo $clan->getTotemThumbnailPath(); ?>" /></a>
                                    </div>
                                </td>
                                <td class="padding0" style="padding-top:10px;">
                                	<div style="position:relative;">
                                    <h2><a class="clanpopup" id="clan_<?php echo $line['id']; ?>" href="<?php echo $this->baseUrl('clan/view/id/'.encode($line['id'])); ?>" style="width:100%; display:block;" title="View <?php echo $line['Clan Name']; ?>"><?php echo snippet($line['Clan Name'], 32, '...'); ?></a></h2>
                                    <table class="itemlist table noborder margin0">
                                    	<tr>
                                        	<td style="width:15%;"><label class="control-label">Clan Head: </label></td>
                                            <td><?php echo $clan->getHeadTitle(); ?></td>
                                        </tr>
                                        <tr>
                                        	<td><label class="control-label"><?php echo $this->translate("clan_obutaka_label"); ?>: </label></td>
                                            <td><?php echo $clan->getObutakaSsaza(); ?></td>
                                        </tr>
                                        <tr>
                                        	<td><label class="control-label">Akabiro:</label></td>
                                            <td><?php echo isEmptyString($clan->getAkabbiro()) ? '--': $clan->getAkabbiro(); ?></td>
                                        </tr>
                                        <tr>
                                        	<td><label class="control-label">Omubala:</label></td>
                                            <td style="padding-right:25px; padding-bottom:15px;"><?php echo isEmptyString($clan->getOmubala()) ? '--': nl2br($clan->getOmubala()); ?></td>
                                        </tr>
                                    </table>
                                    <a class="btn btn-primary btn-blue btn-mini" style="position:absolute; top:5px; right:20px;" href="<?php echo $this->baseUrl('clan/view/id/'.encode($line['id'])); ?>">View Full Profile</a>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        
                    </li>
                <?php } } ?>    
            </ul>
            <?php echo $paginate->getPaginationLinks(); ?>  
            <div style="margin-bottom:15px;"><?php echo $this->listcountdropdown; ?></div>
          <?php } ?>
        </div>
    </form>
    </div>
    <?php require APPLICATION_PATH."/views/scripts/index/righthandband.phtml"; ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
