<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$useraccount = new UserAccount(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("useraccount_pagetitle_new"); 
	$posturl = $this->baseUrl("profile/create");
	$button_title = $this->translate("useraccount_button_save_label"); 
	
	if (!isEmptyString($request->id)) {
		$useraccount->populate(decode($request->id));
		$title = $this->translate("useraccount_pagetitle_edit"); 
		$button_title = $this->translate("useraccount_button_edit_label");
		$posturl = $this->baseUrl("profile/edit"); 
	}
	
	$isadmin = true; 
	if($userid != $useraccount->getID()){
		# admin user is view another profile
		// $userupdatingownaccount = false; 
	} 
	
	$lookupaclgroups = new LookupType();
	$lookupaclgroups->setName("ALL_ACL_GROUPS"); 
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$useraccount->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#profileform").validate({		
			// define the validation rules one field at a time
			rules: {
				firstname: "required",
				lastname: "required",
				email: {
					"required": true, 
					email: true
				},				
				"usergroups_groupid[]": {
					"required": true,
					"minlength": 1
				} 
			}, 
			// the messages for each of the fields being validated
			messages: {				
				firstname: "<?php echo $this->translate("useraccount_firstname_error"); ?>",
				lastname: "<?php echo $this->translate("useraccount_lastname_error"); ?>",
				email: {
					"required": "<?php echo $this->translate("useraccount_email_error"); ?>", 
					"email": "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
				},				
			 	"usergroups_groupid[]": "<?php echo $this->translate("useraccount_group_error");?>"
			}
		});
	}); 
</script>

<h2><?php echo $title; ?></h2>
<form id="profileform" action="<?php echo $posturl; ?>" method="post">
	<table class="formtable">
		<tr class="sectionheading">
			<td colspan="2"><?php echo $this->translate("useraccount_section_general"); ?></td>
		</tr>
		<?php if ($sessionhaserror) { ?>
		<tr>
			<td class="label">&nbsp;</td>
			<td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
		</tr>
		<?php } ?>
		<tr>
			<td class="label">&nbsp;</td>
			<td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_salutation_label"); ?>:</td>
			<td class="value">
			<?php 	
				# lookup for salutations
				$salutionlookup = new LookupType();		
				$salutionlookup->setName("SALUTATION");
	
				$salutiondropdown = new Zend_Form_Element_Select('salutation',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $salutionlookup->getOptionValuesAndDescription()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper')
								)
							);
				
				$salutiondropdown->setValue($useraccount->getSalutation());				
				echo $salutiondropdown->render();	
			?><div id='salution_error'></div></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_firstname_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
			<td class="value"><input name="firstname" id="firstname" type="text" value="<?php echo $useraccount->getFirstName(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_lastname_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
			<td class="value"><input name="lastname" id="lastname" type="text" value="<?php echo $useraccount->getLastName(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_othername_label"); ?>:</td>
			<td class="value"><input name="othername" id="othername" type="text" value="<?php echo $useraccount->getOtherName(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_gender_label"); ?>:</td>
			<td class="value">
				<input type='radio' name='gender' id='r_female' class='<?php echo $useraccount->isFemale() ? 1 : 0; ?>' value="F" /><?php echo $this->translate("useraccount_gender_female_label"); ?>
				<input type='radio' name='gender' id='r_male' class='<?php echo $useraccount->isMale() ? 1 : 0; ?>' value="M" /><?php echo $this->translate("useraccount_gender_male_label"); ?>
			</td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_username_label"); ?>:</td>
			<td class="value"><input name="username" id="username" type="text" value="<?php echo $useraccount->getUserName(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_email_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
			<td class="value"><input name="email" id="email" type="text" value="<?php echo $useraccount->getEmail(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_email2_label"); ?>:</td>
			<td class="value"><input name="email2" id="email2" type="text" value="<?php echo $useraccount->getEmail2(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_password_label"); ?>:</td>
			<td class="value">
				<?php if(!$isadmin){ ?>
					<a href="<?php echo $this->baseUrl('profile/changepassword'); ?>" title="<?php echo $this->translate("useraccount_changepassword_label"); ?>"><?php echo $this->translate("useraccount_changepassword_label"); ?></a>&nbsp;				
				<?php }else{ ?>
					<a href="<?php echo $this->baseUrl('profile/resetpassword'); ?>" title="<?php echo $this->translate("useraccount_resetpassword_label"); ?>"><?php echo $this->translate("useraccount_resetpassword_label"); ?></a>
				<?php } ?>
			</td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_phone_label"); ?>:</td>
			<td class="value"><input name="phone" id="phone" type="text" value="<?php echo $useraccount->getPhone(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_phone2_label"); ?>:</td>
			<td class="value"><input name="phone2" id="phone2" type="text" value="<?php echo $useraccount->getPhone2(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_fax_label"); ?>:</td>
			<td class="value"><input name="fax" id="fax" type="text" value="<?php echo $useraccount->getFax(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_address_label"); ?>:</td>
			<td class="value"><textarea id="address" name="address" class="expanding"><?php echo $useraccount->getAddress(); ?></textarea></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_country_label"); ?>:</td>
			<td class="value">***<?php //echo $useraccount->getCountry(); ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_city_label"); ?>:</td>
			<td class="value"><input type="text" name="city" id="city" value="<?php echo $useraccount->getCity(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_state_label"); ?>:</td>
			<td class="value">
				<?php
					$statedropdown = new Zend_Form_Element_Select('state',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getStates()),
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('filterselect')
										)
									);
					$statedropdown->setValue($useraccount->getState()); 
					echo $statedropdown->render(); 
				  ?>
			</td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_zipcode_label"); ?>:</td>
			<td class="value"><input type="text" name="zipcode" id="zipcode" value="<?php echo $useraccount->getZipcode(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_website_label"); ?>:</td>
			<td class="value"><input type="text" name="website" id="website" value="<?php echo $useraccount->getWebsite(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_securityquestion_label"); ?>:</td>
			<td class="value"><input type="text" name="securityquestion" id="securityquestion" value="<?php echo $useraccount->getSecurityQuestion(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_securityanswer_label"); ?>:</td>
			<td class="value"><input type="text" name="securityanswer" id="securityanswer" value="<?php echo $useraccount->getSecurityAnswer(); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_dateofbirth_label"); ?>:</td>
			<td class="value"><input type="text" class="datefield" name="dateofbirth" id="dateofbirth" value="<?php echo changeMySQLDateToPageFormat($useraccount->getDateOfBirth()); ?>" /></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_biography_label"); ?>:</td>
			<td class="value"><textarea id="biography" name="biography" class="expanding"><?php echo $useraccount->getBiography(); ?></textarea></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_photo_label"); ?>:</td>
			<td class="value"><?php echo $useraccount->getPhoto(); ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $this->translate("useraccount_notes_label"); ?>:</td>
			<td class="value"><textarea id="notes" name="notes" class="expanding"><?php echo $useraccount->getNotes(); ?></textarea></td>
		</tr>
		<?php if($isadmin){ ?>
			<tr>
				<td class="label"><?php echo $this->translate("useraccount_section_groups"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
				<td class="value">
					<?php 	
						$cb = new Zend_Form_Element_MultiCheckbox('usergroups_groupid',
									array(
										'multiOptions' => $lookupaclgroups->getOptionValuesFromQuery(), 
										'view' => new Zend_View(),
										'decorators' => array('ViewHelper')
									)
								);
						$cb->setValue($useraccount->getGroupIDs()); 
						$cb->setSeparator(' ');  
						echo $cb->render();	
					?></td>
			</tr>
			<tr>
				<td class="label"><?php echo $this->translate("useraccount_isactive_label"); ?>:</td>
				<td class="value">
					<input type="radio" name="isactive" id="r_yes" class="<?php echo $useraccount->isActivated() ? 1 : 0; ?>" value="1" /><?php echo $this->translate("global_yes_label"); ?>
					<input type="radio" name="isactive" id="r_no" class="<?php echo !$useraccount->isActivated() ? 1 : N ; ?>" value="0" /><?php echo $this->translate("global_no_label"); ?>
				</td>
			</tr>		
		<?php } ?>
  </table>  
  <table class="formactions">  
	<tr>
		<td>
			<a href="<?php echo $this->viewUrl(array("id" => encode($useraccount->getID()))); ?>" title="<?php echo $this->translate("global_button_cancel"); ?>"></a><?php echo $this->translate("global_button_cancel"); ?>
			<button type="submit" class="positiveaction" id="submit" name="submit" title="<?php echo $button_title; ?>"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
			<input type="hidden" name="entityname" value="UserAccount" />
			<input type="hidden" id="id" name="id" value="<?php echo encode($useraccount->getID()); ?>" />
		</td>
	</tr>  
</table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
