<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_recoverpassword_confirm"); 
	$this->headTitle($title); 
	
	// the usermaking the payment
	$useraccount = new UserAccount();
	
?>
<style>
#contentcolumn {
	min-height:0;
	height:320px;
}
</style>
<div class="row span12 marginleft0" style="margin:0 auto;">

<span class="span7" style="margin-left:220px;">
	<h1 class="aligncenter"><?php echo $title; ?></h1>
	<table class="table" style="margin-top:20px;">
		<thead>
		 	<tr>			
				<td><div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php //echo $session->getVar(SUCCESS_MESSAGE); ?>Reset instructions sent successfully</div></td>
			</tr>
		</thead>
		<tr>
		  	<td>An email has been sent to you with instructions on how to reset your password. If you don't see the email in your inbox, please check your <b>Junk</b> or <b>Spam</b> mail folder.<br /><br />		

        For any assistance please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />
			</td>
		</tr>
	</table>
</span>
</div>	
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
