<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_resetpassword");
	$this->headTitle($title);  
	
	$useraccount = new UserAccount(); 
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
	
?>
<script>
$(document).ready(function(){
	$("#loginheader").remove();
	$("#contentwrapper").removeClass('well');
});
</script>
<style>
#contentwrapper {
	border:none;
}
#contentcolumn {
	min-height:0;
	height:320px;
}
.table.list {
	width:100%;
}
#loginwidget .table.list thead {
	/*background: -moz-linear-gradient(top, #296E8D 0%, #338AB0 47%, #5CA1C0 100%); */
	color:#fff;
	background:none;
	background-color:#0073b2;
}
#loginwidget .table.list thead tr td a {
	color:#fff;
}
#loginwidget h3 {
	color:#f1f1f1;
}
#loginwidget.well {
    background-color: #F7F7F7;
    border: 1px solid #80B0D4;
    border-radius: 8px 8px 8px 8px;
   	margin-bottom: 0;
    padding: 2px;
}
</style>
<span class="span6 offset3">
	<form class="form-horizontal" id="loginform" action="<?php echo $this->baseUrl('user/processresetpassword'); ?>" method="post">
        <div class="well padding2" id="loginwidget" style="margin-top:15px;">
            <table class="table noborder margin0 list">
                <thead>
                   <tr>
                       <td colspan="2" style="padding:6px;"><h3><?php echo $title; ?></h3></td>
                   </tr>
                </thead>
                <?php if($sessionhaserror) { ?>
                <tr>			
                   <td colspan="2"><div class="alert alert-error margin0"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                </tr>
                <?php } else { ?>
                <tr>			
                   <td colspan="2"></td>
                </tr>
                <?php } ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                <tr>			
                   <td colspan="2"><div class="alert alert-success"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div></td>
                </tr>
                <?php } ?> 
                <tr><td colspan="2">Please specify a new Password for your Account</td></tr>
                <tr class="tablespacer">
                   <td class="span2"><label class="control-label" for="email"><?php echo $this->translate("useraccount_password_label"); ?>:<?php echo $this->translate("global_required_field_marker"); ?></label></td>
                   <td><input name="password" id="password" type="password" /></td>
                </tr> 
                <tr>
                   <td><label class="control-label" for="email"><?php echo $this->translate("useraccount_password_confirm_label"); ?>:<?php echo $this->translate("global_required_field_marker"); ?></label></td>
                   <td><input name="confirmpassword" id="confirmpassword" type="password" /></td>
                </tr>       
            </table>
            <div class="form-actions noborder padding0">
                <button id="reset" class="btn btn-primary btn-gold" type="submit" title="Save Password"><i class="icon-lock"></i> Save Password</button>&nbsp;&nbsp;
                <input name="id" type="hidden" value="<?php echo $request->id; ?>" />
            </div>
        </div>
	</form>
</span>   
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
<script>
$(document).ready(function() {
		$("#email").focus();
		$("#loginform").validate({		
			// define the validation rules one field at a time
			rules: {
				password: {
					required: true,
					maxlength: <?php echo $config->password->maxlength; ?>,
					minlength: <?php echo $config->password->minlength; ?>
				},			
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}
			}, 
			messages: {
				password: {
					required: "<?php echo $this->translate("useraccount_password_error"); ?>",
					maxlength: "<?php echo sprintf($this->translate("useraccount_password_error_maxlength"), $config->password->maxlength); ?>",
					minlength: "<?php echo sprintf($this->translate("useraccount_password_error_minlength"), $config->password->minlength); ?>"					
				},
				confirmpassword: {
					required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
				}
			}
		}); 
	
}); 
</script>
<style>
.form-horizontal .control-label {
	text-align:right;
}
.form-horizontal .form-actions {
    text-align: left;
}
</style>
