<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_recoverpassword_confirm"); 
	$this->headTitle($title); 
	
	// the usermaking the payment
	$useraccount = new UserAccount();
	
?>
<style>
#contentcolumn {
	min-height:0;
	height:320px;
}
</style>
<div class="row span12 marginleft0" style="margin:0 auto;">

<span class="span7" style="margin-left:220px;">
	<h1 class="aligncenter"><?php echo $title; ?></h1>
	<table class="table" style="margin-top:20px;">
		<thead>
		 	<tr>			
				<td><div class="alert alert-success"><a class="close" data-dismiss="alert">×</a>You have sucessfully reset your password.</div></td>
			</tr>
		</thead>
        <tr>
	        <td class="centeralign">
	            You can now log in using your new Password.<br><br />
	            <a class="btn btn-primary btn-gold" href="<?php echo $this->baseUrl("user/logout")?>"><i class="icon-lock"></i> Login</a><br /><br>
	        </td>
	    </tr>
	</table>
</span>
</div>	
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
